/* Start master details section */

const master = {
  asset_category: [
    {
      ASSET_CATEGORYID_SYSTEM: '1',
      ASSET_CATEGORY_CODE: 'INST',
      ASSET_CATEGORY_NAME: 'Instrumentation',
    },
  ],
  asset_condition: [
    {
      ASSET_CONDITIONID_SYSTEM: '1',
      ASSET_CONDITION_CODE: 'GC',
      ASSET_CONDITION_NAME: 'Good Condition',
    },
  ],
  asset_status: [
    {
      ASSET_STATUSID_SYSTEM: '1',
      ASSET_STATUS_CODE: 'ASN',
      ASSET_STATUS_NAME: 'Assigned',
    },
  ],
  division: [
    {
      DIVISIONID_SYSTEM: '2',
      DIVISION_SCODE: 'ZS',
      DIVISION_CODE: 'ZYME',
      DIVISION_NAME: 'ZYME Solutions',
    },
  ],
  location: [
    {
      LOCATIONID_SYSTEM: '12',
      LOCATION_CODE: 'BBF1',
      LOCATION_NAME: 'B-Block - Floor-1',
    },
  ],
  department: [
    {
      DEPARTMENTID_SYSTEM: '12',
      DEPARTMENT_CODE: 'INST',
      DEPARTMENT_NAME: 'Instrumentation',
    },
  ],
  designation: [
    {
      DESIGNATIONID_SYSTEM: '2',
      DESIGNATION_CODE: 'TECH',
      DESIGNATION_NAME: 'Technician',
    },
  ],
  nation: [
    {NATIONID_SYSTEM: '2', NATION_CODE: 'KRC', NATION_NAME: 'Bangalore South'},
  ],
  vendor_details: [
    {
      VENDORID_SYSTEM: '2',
      VENDOR_CODE: 'PHT',
      VENDOR_NAME: 'PowerHealth Technologies',
      NATIONID_SYSTEM: '878',
      VENDOR_ADDRESS: '638, 5th Cross, 8th Main, RPC Layout',
      CONTACT_NO: '9900260176',
      CONTACT_NAME: 'Chelvan',
      CONTACT_EMAILID: 'silambu.chelvan@powerhealthtech.com',
      KEY_CONTACT: 'Yes',
    },
  ],
  maint_type: [
    {
      MAINT_TYPEID_SYSTEM: '7',
      MAINT_TYPE_CODE: 'WO',
      MAINT_TYPE_NAME: 'Workorder',
    },
  ],
  maint_category: [
    {
      MAINT_CATEGORYID_SYSTEM: '2',
      MAINT_CATEGORY_CODE: 'CONBSD',
      MAINT_CATEGORY_NAME: 'Condition based',
      MAINT_TYPEID_SYSTEM: '7',
    },
  ],
  job_status: [
    {
      JOB_STATUSID_SYSTEM: '2',
      JOB_STATUS_CODE: 'CLS',
      JOB_STATUS_NAME: 'Closed',
    },
  ],
  workflow_event: [
    {
      TRANS_EVENTID_SYSTEM: '6',
      TRANS_EVENT_CODE: 'CRE',
      TRANS_EVENT_NAME: 'Created',
      BUTTON_NAME: 'Create',
      BUTTON_COLOR: 'btn-success',
      BUTTON_ICON: 'fa text-white fa-plus',
      EVENT_TYPEID_SYSTEM: '2',
      EVENT_TEXT_COLOR: 'white',
      EVENT_BG_COLOR: '#be6b1e',
    },
  ],
  workflow_event_type: [
    {
      EVENT_TYPEID_SYSTEM: '2',
      EVENT_TYPE_CODE: 'WRKFLW',
      EVENT_TYPE_NAME: 'Work Flow',
    },
  ],
  resource_category: [
    {
      RESOURCE_CATEGORYID_SYSTEM: '1',
      RESOURCE_CATEGORY_CODE: 'ENGG',
      RESOURCE_CATEGORY_NAME: 'Engineer',
      RESOURCE_TYPEID_SYSTEM: '2',
    },
  ],
  resource_type: [
    {
      RESOURCE_TYPEID_SYSTEM: '2',
      RESOURCE_TYPE_CODE: 'PERSON',
      RESOURCE_TYPE_NAME: 'Person',
    },
  ],
  app_users: [
    {
      USERID_SYSTEM: '12',
      USER_CODE: '',
      SALUTATION: 'Mr',
      FIRST_NAME: '',
      MIDDLE_NAME: '',
      LAST_NAME: '',
      PRIMARY_DIVISION_ID: '1',
      DEPARTMENTID_SYSTEM: '2',
      DESIGNATIONID_SYSTEM: '2',
      MOBILE_NO: '',
      EMAIL_ID: '',
      IS_CONTRACTOR: 'Yes',
      VENDORID_SYSTEM: '1',
      IS_SITE_DEPLOYED: 'Yes',
    },
  ],
  item_details: [
    {
      ITEMID_SYSTEM: '12',
      ITEM_CODE: 'INST0002',
      ITEM_NAME: 'AIR Regulating Filter 1/4 INCH',
      ASSET_CATEGORYID_SYSTEM: '4',
      ITEM_VENDOR_ID: '1',
      ITEM_OWNER_DEPT_ID: '3',
      PURCHASE_UOM_ID: '8',
      ISSUE_UOM_ID: '8',
      ITEM_MAKE: 'SHAVO',
      ITEM_MODEL_NO: '',
      ITEM_UNIT_PRICE: '400.73',
      ITEM_GUNIT_PRICE: '1600.00',
      LASTPUR_UNIT_PRICE: '1.00',
      LASTPUR_GUNIT_PRICE: '1636.36',
      MIN_STOCK_QTY: '0',
      MAX_STOCK_QTY: '0',
      REORDER_LEVEL_QTY: '0',
      MIN_ORDER_QTY: '0',
      QUALITY_CHECK_REQD: 'Yes',
      TEST_CERT_REQD: 'Yes',
      STATIC_AUDIT_REQD: 'No',
      INSURANCE_REQD: 'No',
      IS_CAPITAL_ASSET: 'No',
      IS_EXPIRY: 'No',
      IS_CRITICAL: 'Yes',
      IS_CHEMICAL: 'No',
      IS_RADIOACTIVE: 'No',
      BLOCK_PURCHASE: 'Yes',
      BLOCK_ISSUE: 'No',
      LOCAL_PURCHASE: 'No',
      CTRLD_STORAGE: 'No',
      ITEM_SPECIAL_INST: '',
      INIT_PURCHASE: 'TTE',
      INSTALLED_QTY: '',
    },
  ],
  uom_details: [
    {
      UOMID_SYSTEM: '12',
      UOM_CODE: 'mg',
      UOM_NAME: 'Milligram',
      IS_PURCHASE: 'No',
      CONV_FACTOR: '1',
    },
  ],
  activity_setup: [
    {
      DEPARTMENTID_SYSTEM: '12',
      DEPARTMENT_CODE: 'INST',
      DEPARTMENT_NAME: 'Instrumentation',
    },
  ],
  checklist_activity: [
    {
      CHECKLIST_ACTIVITYID_SYSTEM: '1',
      ACTIVITY_NAME: 'Check the air conditioner clean and dust free',
      FREQUENCYID_SYSTEM: '1',
      RESULT_TYPEID_SYSTEM: '2',
      RESULT_CODEID_SYSTEM: '5',
      NORMAL_RESULT_ID: '10',
      ABNORMAL_RESULT_ID: '11',
      SEQUENCE_NO: '1',
    },
  ],
  datalog_activity: [
    {
      DATALOG_ACTIVITYID_SYSTEM: '1',
      PARAMETER_NAME: 'Workstation - GF Temperature',
      RESULT_UOMID_SYSTEM: '1',
      FREQUENCYID_SYSTEM: '9',
      RANGE_LOW: '21',
      RANGE_HIGH: '25',
      ALERT_LOW: '18',
      ALERT_HIGH: '25',
      SEQUENCE_NO: '1',
    },
  ],
  result_type: [
    {
      RESULT_TYPEID_SYSTEM: '2',
      RESULT_TYPE_CODE: 'DRDN',
      RESULT_TYPE_NAME: 'Dropdown',
    },
  ],
  result_code: [
    {RESULT_CODEID_SYSTEM: '1', RESULT_CODE: 'HML', RESULT_CODE_NAME: 'H-M-L'},
  ],
  frequency: [
    {
      FREQUENCYID_SYSTEM: '12',
      FREQUENCY_CODE: 'WK',
      FREQUENCY_NAME: 'Weekly',
      FREQ_DURATION: '52',
    },
  ],
  result_uom: [
    {
      RESULT_UOMID_SYSTEM: '23',
      RESULT_UOM_CODE: '%',
      RESULT_UOM_NAME: 'Percentage',
    },
  ],
};

/* End master details section */

/* Start asset details section */

const assets = {
  asset_details: [
    {
      ASSETID_SYSTEM: '5894',
      ASSET_CODE: 'A21ZS001',
      ASSET_NAME: 'DUCTABLE AC- WORKSTATION - 17TR',
      DIVISIONID_SYSTEM: '2',
      ASSET_CATEGORYID_SYSTEM: '4',
      LOCATIONID_SYSTEM: '1',
      DEPARTMENTID_SYSTEM: '3',
      ASSET_STATUSID_SYSTEM: '2',
      ASSET_MAKE: '',
      ASSET_MODEL_NO: '',
      ASSET_SERIAL_NO: '',
      ASSET_BARCODE: '',
      IS_TRACKED: '',
      ASSET_CONDITIONID_SYSTEM: '2',
    },
    {
      ASSETID_SYSTEM: '5894',
      ASSET_CODE: 'A21ZS001',
      ASSET_NAME: 'DUCTABLE AC- WORKSTATION - 17TR',
      DIVISIONID_SYSTEM: '2',
      ASSET_CATEGORYID_SYSTEM: '4',
      LOCATIONID_SYSTEM: '1',
      DEPARTMENTID_SYSTEM: '3',
      ASSET_STATUSID_SYSTEM: '2',
      ASSET_MAKE: '',
      ASSET_MODEL_NO: '',
      ASSET_SERIAL_NO: '',
      ASSET_BARCODE: '',
      IS_TRACKED: '',
      ASSET_CONDITIONID_SYSTEM: '2',
    },
    {
      ASSETID_SYSTEM: '5894',
      ASSET_CODE: 'A21ZS001',
      ASSET_NAME: 'DUCTABLE AC- WORKSTATION - 17TR',
      DIVISIONID_SYSTEM: '2',
      ASSET_CATEGORYID_SYSTEM: '4',
      LOCATIONID_SYSTEM: '1',
      DEPARTMENTID_SYSTEM: '3',
      ASSET_STATUSID_SYSTEM: '2',
      ASSET_MAKE: '',
      ASSET_MODEL_NO: '',
      ASSET_SERIAL_NO: '',
      ASSET_BARCODE: '',
      IS_TRACKED: '',
      ASSET_CONDITIONID_SYSTEM: '2',
    },
    {
      ASSETID_SYSTEM: '5894',
      ASSET_CODE: 'A21ZS001',
      ASSET_NAME: 'DUCTABLE AC- WORKSTATION - 17TR',
      DIVISIONID_SYSTEM: '2',
      ASSET_CATEGORYID_SYSTEM: '4',
      LOCATIONID_SYSTEM: '1',
      DEPARTMENTID_SYSTEM: '3',
      ASSET_STATUSID_SYSTEM: '2',
      ASSET_MAKE: '',
      ASSET_MODEL_NO: '',
      ASSET_SERIAL_NO: '',
      ASSET_BARCODE: '',
      IS_TRACKED: '',
      ASSET_CONDITIONID_SYSTEM: '2',
    },
  ],
};

/* End asset details section */

/* Start maintenance details section */

const maintenance = {
  wo_details: [
    {
      ASSETID_SYSTEM: '1',
      WORKORDERID_SYSTEM: '11',
      WO_NO: 'WO21ZS0010',
      MAINT_TYPEID_SYSTEM: '7',
      MAINT_CATEGORYID_SYSTEM: '2',
      SCHEDULE_DATE: '21-09-2021',
      SHORT_DESC: 'Replace new fire extinguisher',
      DEPARTMENTID_SYSTEM: '12',
      TRANS_EVENTID_SYSTEM: '66',
      USERID_SYSTEM: '1',
      CLS_ASSIGNED_TO: '0',
      JOB_STATUSID_SYSTEM: '2',
      WO_CLOSURE_LOG: '',
      CLOSURE_REMARKS: '',
      effort_details: {
        MAINT_EFFORTID_SYSTEM: '9',
        REF_NO: '',
        WO_NO: 'WO21ZS0010',
        PLANNED_EFFORT_TOTAL: '30.00',
        ACTUAL_EFFORT_TOTAL: '0.00',
        RESOURCE_COMBO: '1,2',
        CREATED_BY: '26',
        CREATED_DATE_TIME: '2021-09-21T05:56:33Z',
        UPDATED_BY: '26',
        UPDATED_DATE_TIME: '2021-09-21T07:11:35Z',
        '1_PLANNED_EFFORT': '20.00',
        '1_ACTUAL_EFFORT': '0.00',
        '2_PLANNED_EFFORT': '10.00',
        '2_ACTUAL_EFFORT': '0.00',
        '3_PLANNED_EFFORT': '0.00',
        '3_ACTUAL_EFFORT': '0.00',
        '4_PLANNED_EFFORT': '0.00',
        '4_ACTUAL_EFFORT': '0.00',
        '5_PLANNED_EFFORT': '0.00',
        '5_ACTUAL_EFFORT': '0.00',
        '6_PLANNED_EFFORT': '0.00',
        '6_ACTUAL_EFFORT': '0.00',
        '7_PLANNED_EFFORT': '0.00',
        '7_ACTUAL_EFFORT': '0.00',
        '8_PLANNED_EFFORT': '0.00',
        '8_ACTUAL_EFFORT': '0.00',
        '9_PLANNED_EFFORT': '0.00',
        '9_ACTUAL_EFFORT': '0.00',
        '10_PLANNED_EFFORT': '0.00',
        '10_ACTUAL_EFFORT': '0.00',
        '11_PLANNED_EFFORT': '0.00',
        '11_ACTUAL_EFFORT': '0.00',
        RESOURCE_CATEGORY_COUNT: 2,
        0: {
          '1_PLANNED_EFFORT': '20.00',
          '1_ACTUAL_EFFORT': '0.00',
          RESOURCE_CATEGORY_ID: '1',
        },
        1: {
          '2_PLANNED_EFFORT': '10.00',
          '2_ACTUAL_EFFORT': '0.00',
          RESOURCE_CATEGORY_ID: '2',
        },
      },
      spares_details: [
        {
          MAINT_SPARESID_SYSTEM: '6',
          REF_NO: '',
          WO_NO: 'WO21ZS0010',
          ITEMID_SYSTEM: '2938',
          REQ_QTY: '1',
          REQ_AVAIL_QTY: '44',
          CONSUMED_QTY: '0',
          UNIT_COST: '0.00',
          REQ_TOTAL_COST: '0.00',
          CONSUMED_TOTAL_COST: '0.00',
          IS_REPLACED: '',
          IS_DELETE: 'No',
          CREATED_BY: '1',
          CREATED_DATE_TIME: '2021-02-22T08:43:03Z',
          UPDATED_BY: '0',
          UPDATED_DATE_TIME: '',
          DELETED_BY: '0',
          DELETED_DATE_TIME: '',
        },
        {
          MAINT_SPARESID_SYSTEM: '7',
          REF_NO: '',
          WO_NO: 'WO21ZS0010',
          ITEMID_SYSTEM: '2939',
          REQ_QTY: '2',
          REQ_AVAIL_QTY: '13',
          CONSUMED_QTY: '0',
          UNIT_COST: '0.00',
          REQ_TOTAL_COST: '0.00',
          CONSUMED_TOTAL_COST: '0.00',
          IS_REPLACED: '',
          IS_DELETE: 'No',
          CREATED_BY: '1',
          CREATED_DATE_TIME: '2021-02-22T08:43:03Z',
          UPDATED_BY: '0',
          UPDATED_DATE_TIME: '',
          DELETED_BY: '0',
          DELETED_DATE_TIME: '',
        },
      ],
    },
  ],
};

/* End maintenance details section */

export {assets, maintenance};
